"""initial schema

Revision ID: 66dd00beb93a
Revises: 
Create Date: 2026-08-31 04:13:24.336493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66dd00beb93a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('manual_source_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_source_texts_user_id'), 'manual_source_texts', ['user_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('usage_rights', sa.Text(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_user_id'), 'media_assets', ['user_id'], unique=False)
    op.create_table('monitored_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('x_user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_post_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_baseline', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_accounts_user_id'), 'monitored_accounts', ['user_id'], unique=False)
    op.create_table('x_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('x_user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_method', sa.String(length=16), nullable=False),
    sa.Column('session_state_encrypted', sa.Text(), nullable=False),
    sa.Column('session_valid', sa.Boolean(), nullable=False),
    sa.Column('session_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('persona_prompt', sa.Text(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('posts_per_day', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.String(length=5), nullable=False),
    sa.Column('window_end', sa.String(length=5), nullable=False),
    sa.Column('min_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_x_accounts_user_id'), 'x_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_x_accounts_x_user_id'), 'x_accounts', ['x_user_id'], unique=False)
    op.create_index('uq_user_xaccount', 'x_accounts', ['user_id', 'x_user_id'], unique=True, postgresql_where=sa.text("x_user_id <> ''"))
    op.create_table('retweet_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_tweet_id', sa.String(length=64), nullable=False),
    sa.Column('origin_x_account_id', sa.Integer(), nullable=True),
    sa.Column('target_x_account_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('retweet_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['origin_x_account_id'], ['x_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_x_account_id'], ['x_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retweet_jobs_scheduled_at'), 'retweet_jobs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_retweet_jobs_status'), 'retweet_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_retweet_jobs_target_x_account_id'), 'retweet_jobs', ['target_x_account_id'], unique=False)
    op.create_index(op.f('ix_retweet_jobs_user_id'), 'retweet_jobs', ['user_id'], unique=False)
    op.create_table('source_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x_post_id', sa.String(length=96), nullable=False),
    sa.Column('monitored_account_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author_username', sa.String(length=64), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('reposts', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('media_metadata', sa.JSON(), nullable=False),
    sa.Column('original_url', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['monitored_account_id'], ['monitored_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_posts_content_hash'), 'source_posts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_posts_monitored_account_id'), 'source_posts', ['monitored_account_id'], unique=False)
    op.create_index(op.f('ix_source_posts_score'), 'source_posts', ['score'], unique=False)
    op.create_index(op.f('ix_source_posts_user_id'), 'source_posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_source_posts_x_post_id'), 'source_posts', ['x_post_id'], unique=True)
    op.create_table('ai_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_post_id', sa.Integer(), nullable=True),
    sa.Column('target_account_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_post_id'], ['source_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_account_id'], ['x_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generations_user_id'), 'ai_generations', ['user_id'], unique=False)
    op.create_table('content_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_post_id', sa.Integer(), nullable=True),
    sa.Column('target_x_account_id', sa.Integer(), nullable=True),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('media_reference', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('block_reason', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_post_id'], ['source_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_x_account_id'], ['x_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_candidates_content_hash'), 'content_candidates', ['content_hash'], unique=False)
    op.create_index(op.f('ix_content_candidates_status'), 'content_candidates', ['status'], unique=False)
    op.create_index(op.f('ix_content_candidates_target_x_account_id'), 'content_candidates', ['target_x_account_id'], unique=False)
    op.create_index(op.f('ix_content_candidates_user_id'), 'content_candidates', ['user_id'], unique=False)
    op.create_table('candidate_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_candidate_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_candidate_id'], ['content_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_media_content_candidate_id'), 'candidate_media', ['content_candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_media_media_asset_id'), 'candidate_media', ['media_asset_id'], unique=False)
    op.create_table('scheduled_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('x_account_id', sa.Integer(), nullable=False),
    sa.Column('content_candidate_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('published_post_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_candidate_id'], ['content_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['x_account_id'], ['x_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_posts_scheduled_at'), 'scheduled_posts', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_status'), 'scheduled_posts', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_user_id'), 'scheduled_posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_x_account_id'), 'scheduled_posts', ['x_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_posts_x_account_id'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_user_id'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_status'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_scheduled_at'), table_name='scheduled_posts')
    op.drop_table('scheduled_posts')
    op.drop_index(op.f('ix_candidate_media_media_asset_id'), table_name='candidate_media')
    op.drop_index(op.f('ix_candidate_media_content_candidate_id'), table_name='candidate_media')
    op.drop_table('candidate_media')
    op.drop_index(op.f('ix_content_candidates_user_id'), table_name='content_candidates')
    op.drop_index(op.f('ix_content_candidates_target_x_account_id'), table_name='content_candidates')
    op.drop_index(op.f('ix_content_candidates_status'), table_name='content_candidates')
    op.drop_index(op.f('ix_content_candidates_content_hash'), table_name='content_candidates')
    op.drop_table('content_candidates')
    op.drop_index(op.f('ix_ai_generations_user_id'), table_name='ai_generations')
    op.drop_table('ai_generations')
    op.drop_index(op.f('ix_source_posts_x_post_id'), table_name='source_posts')
    op.drop_index(op.f('ix_source_posts_user_id'), table_name='source_posts')
    op.drop_index(op.f('ix_source_posts_score'), table_name='source_posts')
    op.drop_index(op.f('ix_source_posts_monitored_account_id'), table_name='source_posts')
    op.drop_index(op.f('ix_source_posts_content_hash'), table_name='source_posts')
    op.drop_table('source_posts')
    op.drop_index(op.f('ix_retweet_jobs_user_id'), table_name='retweet_jobs')
    op.drop_index(op.f('ix_retweet_jobs_target_x_account_id'), table_name='retweet_jobs')
    op.drop_index(op.f('ix_retweet_jobs_status'), table_name='retweet_jobs')
    op.drop_index(op.f('ix_retweet_jobs_scheduled_at'), table_name='retweet_jobs')
    op.drop_table('retweet_jobs')
    op.drop_index('uq_user_xaccount', table_name='x_accounts', postgresql_where=sa.text("x_user_id <> ''"))
    op.drop_index(op.f('ix_x_accounts_x_user_id'), table_name='x_accounts')
    op.drop_index(op.f('ix_x_accounts_user_id'), table_name='x_accounts')
    op.drop_table('x_accounts')
    op.drop_index(op.f('ix_monitored_accounts_user_id'), table_name='monitored_accounts')
    op.drop_table('monitored_accounts')
    op.drop_index(op.f('ix_media_assets_user_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_manual_source_texts_user_id'), table_name='manual_source_texts')
    op.drop_table('manual_source_texts')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
